{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Factory service requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service\", stream=\"factory\"} | json"
    }
   ]
  },
  {
   "title": "Database requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service\", stream=\"db\"} | json"
    }
   ]
  },
  {
   "title": "unhandled exceptions",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service\", stream=\"error\"} | json"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"jwt-pizza-service\", stream=\"http\"} | json"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum( rate(endpoint_latency_milliseconds_total{source=\"jwt-pizza-service\"}[$__rate_interval]) )\n/\nsum( rate(http_requests_total{source=\"jwt-pizza-service\"}[$__rate_interval]) )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(pizza_creation_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])\n/\nclamp_min(rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m]), 0.000001)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue/min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_cents_total{source=\"jwt-pizza-service\"}[1m]) * 60 / 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sold/Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[$__interval]) * 60",
     "legendFormat": "{{sold/min}}"
    },
    {
     "expr": "rate(pizza_failures_total{source=\"jwt-pizza-service\"}[$__interval]) * 60",
     "legendFormat": "{{fail/min}}"
    }
   ]
  },
  {
   "title": "CPU/Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{memory_usage}}"
    },
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{cpu_usage}}"
    }
   ]
  },
  {
   "title": "Success Login and Failure Login",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(auth_attempts_total{source=\"jwt-pizza-service\",outcome=\"success\"}[1m]) * 60",
     "legendFormat": "{{success}}"
    },
    {
     "expr": "rate(auth_attempts_total{source=\"jwt-pizza-service\",outcome=\"failure\"}[1m]) * 60",
     "legendFormat": "{{failure}}"
    }
   ]
  },
  {
   "title": "active user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{active_users}}"
    }
   ]
  },
  {
   "title": "Http request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "{{TOTAL}}"
    },
    {
     "expr": "sum by (method) (rate(http_requests_total{source=\"jwt-pizza-service\",method=\"GET\"}[1m])) * 60",
     "legendFormat": "{{get}}"
    },
    {
     "expr": "sum by (method) (rate(http_requests_total{source=\"jwt-pizza-service\",method=\"POST\"}[1m])) * 60",
     "legendFormat": "{{POST}}"
    },
    {
     "expr": "sum by (method) (rate(http_requests_total{source=\"jwt-pizza-service\",method=\"PUT\"}[1m])) * 60",
     "legendFormat": "{{PUT}}"
    },
    {
     "expr": "sum by (method) (rate(http_requests_total{source=\"jwt-pizza-service\",method=\"DELETE\"}[1m])) * 60",
     "legendFormat": "{{DELETE}}"
    }
   ]
  }
 ]
}